#!/usr/bin/env python3
"""Offline reference implementation of the GTool MCU_MAIN packet encoder.

This script does NOT open a serial port or flash a device. It reconstructs the
frames generated by GTool 2.0.6 for review and porting to another platform.
"""
from __future__ import annotations

import argparse
import hashlib
import math
from pathlib import Path

PACKET_SIZE = 1024


def checksum(data: bytes | bytearray, mode: int) -> int:
    low = sum(data) & 0xFF
    if mode == 13:
        return (-low) & 0xFF
    if mode == 18:
        return low
    raise ValueError("mode must be 13 or 18")


def command_frame(command: tuple[int, int], flag: int, mode: int) -> bytes:
    prefix = bytes((0xA5, 0x5B)) if mode == 13 else bytes((0x50, 0x56, 0x54))
    body = bytearray(prefix + bytes(command) + bytes((flag,)))
    body.extend(b"\x00" * (mode - 1 - len(body)))
    body.append(checksum(body, mode))
    assert len(body) == mode
    return bytes(body)


def data_frame(firmware: bytes, packet_index: int, mode: int) -> bytes:
    total_packets = math.ceil(len(firmware) / PACKET_SIZE)
    if packet_index < 0 or packet_index >= total_packets:
        raise IndexError("packet index outside firmware range")

    start = packet_index * PACKET_SIZE
    block = bytearray(firmware[start : start + PACKET_SIZE])
    block.extend(b"\xFF" * (PACKET_SIZE - len(block)))

    high = packet_index // 256
    low = packet_index & 0xFF
    if packet_index == total_packets - 1:
        high += 0x80

    frame = bytearray((0xFE, 0xEF, high & 0xFF, low))
    frame.extend(block)
    frame.append(checksum(frame, mode))
    assert len(frame) == 2 + 2 + PACKET_SIZE + 1
    return bytes(frame)


def h(data: bytes) -> str:
    return data.hex(" ").upper()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("firmware", type=Path)
    parser.add_argument("--mode", type=int, choices=(13, 18), default=13)
    parser.add_argument("--flag", type=lambda x: int(x, 0), default=0)
    parser.add_argument("--write-dir", type=Path)
    args = parser.parse_args()

    firmware = args.firmware.read_bytes()
    count = math.ceil(len(firmware) / PACKET_SIZE)
    start = command_frame((0x08, 0x07), args.flag, args.mode)
    confirm = command_frame((0x08, 0x08), args.flag, args.mode)
    first = data_frame(firmware, 0, args.mode)
    last = data_frame(firmware, count - 1, args.mode)

    print(f"Firmware: {args.firmware.name}")
    print(f"Size: {len(firmware)} bytes")
    print(f"SHA-256: {hashlib.sha256(firmware).hexdigest()}")
    print(f"Mode: {args.mode} bytes")
    print(f"Data packets: {count} x {PACKET_SIZE} bytes (last padded with FF)")
    print(f"Start frame:   {h(start)}")
    print(f"Confirm frame: {h(confirm)}")
    print(f"First data header: {h(first[:4])}; checksum={first[-1]:02X}")
    print(f"Last data header:  {h(last[:4])}; checksum={last[-1]:02X}")

    if args.write_dir:
        args.write_dir.mkdir(parents=True, exist_ok=True)
        (args.write_dir / "start.bin").write_bytes(start)
        (args.write_dir / "confirm.bin").write_bytes(confirm)
        for i in range(count):
            (args.write_dir / f"packet-{i:04d}.bin").write_bytes(data_frame(firmware, i, args.mode))
        print(f"Wrote {count + 2} frames to {args.write_dir}")


if __name__ == "__main__":
    main()
