import { describe, expect, it } from "vitest";
import { hexToBytes } from "../../../test/fixtures";
import { buildMcuMainConfirmCommand, buildMcuMainStartCommand } from "../commands";

/**
 * Exact expected bytes from docs/gtool-analysis/packet_reference_output.txt,
 * generated by the reference gtool_packet_reference.py for the real
 * MCU_MAIN_PT-SP-HD14-48G_V1.10.36.bin firmware (flag 00). These frames do
 * not depend on firmware content, so they can be asserted byte-for-byte.
 */
describe("MCU_MAIN initialization commands", () => {
  it("builds the exact 13-byte start command", () => {
    expect(buildMcuMainStartCommand(13)).toEqual(hexToBytes("A5 5B 08 07 00 00 00 00 00 00 00 00 F1"));
  });

  it("builds the exact 13-byte confirm command", () => {
    expect(buildMcuMainConfirmCommand(13)).toEqual(hexToBytes("A5 5B 08 08 00 00 00 00 00 00 00 00 F0"));
  });

  it("builds the exact 18-byte start command", () => {
    expect(buildMcuMainStartCommand(18)).toEqual(
      hexToBytes("50 56 54 08 07 00 00 00 00 00 00 00 00 00 00 00 00 09"),
    );
  });

  it("builds the exact 18-byte confirm command", () => {
    expect(buildMcuMainConfirmCommand(18)).toEqual(
      hexToBytes("50 56 54 08 08 00 00 00 00 00 00 00 00 00 00 00 00 0A"),
    );
  });

  it("produces 13-byte frames that sum to zero modulo 256", () => {
    const frame = buildMcuMainStartCommand(13);
    const sum = frame.reduce((total, byte) => (total + byte) & 0xff, 0);
    expect(sum).toBe(0);
  });
});
